// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEpubFile(arg1) {
  return window['go']['main']['App']['DeleteEpubFile'](arg1);
}

export function GetAppPath() {
  return window['go']['main']['App']['GetAppPath']();
}

export function GetBookList() {
  return window['go']['main']['App']['GetBookList']();
}

export function GetBooksPath() {
  return window['go']['main']['App']['GetBooksPath']();
}

export function GetChapterContentByChapterName(arg1, arg2) {
  return window['go']['main']['App']['GetChapterContentByChapterName'](arg1, arg2);
}

export function GetChapterListByFileName(arg1) {
  return window['go']['main']['App']['GetChapterListByFileName'](arg1);
}

export function GetServerUrl() {
  return window['go']['main']['App']['GetServerUrl']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ParseEpubToTxt(arg1) {
  return window['go']['main']['App']['ParseEpubToTxt'](arg1);
}
