// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEpubFile(arg1:string):Promise<string>;

export function GetAppPath():Promise<string>;

export function GetBookList():Promise<string>;

export function GetChapterContentByChapterName(arg1:string,arg2:string):Promise<string>;

export function GetChapterListByFileName(arg1:string):Promise<string>;

export function GetServerUrl():Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ParseEpubToTxt(arg1:string):Promise<string>;
export function GetBooksPath():Promise<string>;
